# Generated by Django 5.1.3 on 2025-01-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='dep_decription',
            new_name='dep_desription',
        ),
    ]
