# Generated by Django 5.1.3 on 2025-03-03 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
